version: 2.1
jobs:
  build_test_lint:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: | 
            python -m venv venv
            . venv/bin/activate 
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run linting
          command: |             
            . venv/bin/activate 
            python -m flake8
      - run:
          name: Run tests
          command: |            
            . venv/bin/activate 
            python -m pytest

  containerization:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build and push image
          command: |
            docker build -t $DOCKER_USERNAME/ocrproject13:$CIRCLE_SHA1 .
            # I could directly pass the passwd with the -p option. However, using 
            # STDIN prevents the password from ending up in the shell’s history, or log-files.
            echo $DOCKER_PASSWD | docker login -u $DOCKER_USERNAME --password-stdin 
            docker push $DOCKER_USERNAME/ocrproject13:$CIRCLE_SHA1

  deployment:
    working_directory: ~/circleci-python
    machine: true
    steps:
      - checkout
      - run:
          name: login to heroku, build docker image and release image
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            
            printf "machine api.heroku.com
              login $HEROKU_EMAIL
              apikey $HEROKU_TOKEN
            machine git.heroku.com
              login $HEROKU_EMAIL
              apikey $HEROKU_TOKEN
            " > ~/.netrc
            
            heroku container:login
            heroku create oc-lettings-81
            heroku addons:create sentry:free --app=oc-lettings-81
            heroku config:get $SENTRY_DSN
            heroku webhooks:add -i api:release -l notify -u https://sentry.io/api/hooks/release/heroku/4504526256340992/13f4030d03cd8510c51e07f867b664c7d7dab3c56fd69816c6908fcba763cab1/ -a oc-lettings-81
            heroku container:push web --app=oc-lettings-81
            heroku container:release web --app=oc-lettings-81
            

workflows:
  build_deploy:
    jobs:
      - build_test_lint
      - containerization:
          context: project13
          requires:
            - build_test_lint
          filters:
            branches:
              only: master
      - deployment:
          context: project13
          requires:
            - containerization
          filters:
            branches:
              only: master
