version: 2.1
jobs:
  build_test_lint:
    working_directory: ~/circleci-python
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: | 
            python -m venv venv
            . venv/bin/activate 
            pip install -r requirements.txt
            pip uninstall six
            pip install six
      - run:
          name: Run linting
          command: |             
            . venv/bin/activate 
            python -m flake8
      - run:
          name: Run tests
          command: |            
            . venv/bin/activate 
            python -m pytest
            

workflows:
  build_deploy:
    jobs:
      - build_test_lint