version: 2.1
jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
        - name: install dependencies start server
        - command: |
          pip install --upgrade pip 
          python -m venv venv 
          . venv/bin/activate
          pip install -r requirements.txt
          python manage.py runserver

  test:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: "python -m pytest"
  lint:
    working_directory: ~/circleci-python
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: "python -m flake8"
workflows:
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
